site_name: NadekoBot
pages:
- Home: index.md
- About: about.md
- Guides:
    - Windows Guide: guides/comprehensiveguide.md
    - Linux Guide: guides/linuxguide.md
    - OSX Guide: guides/macguide.md
    - Building from Source: guides/fromsource.md
    - Docker Guide: guides/dockerguide.md
- Commands List: https://github.com/Kwoth/NadekoBot/blob/master/commandlist.md
- Permissions System: permissions.md
- JSON Explanations: explanations.md
- Custom Commands: customreactions.md
- Frequently Asked Questions: FAQ.md
- Contribution Guide: contributionguide.md

theme: readthedocs
